/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as OrbitaRouteImport } from './routes/orbita'
import { Route as TowerRouteImport } from './routes/tower'
import { Route as TracesRouteImport } from './routes/traces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitaRoute = OrbitaRouteImport.update({
  id: '/orbita',
  path: '/orbita',
  getParentRoute: () => rootRouteImport,
} as any)
const TowerRoute = TowerRouteImport.update({
  id: '/tower',
  path: '/tower',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/desktop': typeof DesktopRoute
  '/memory': typeof MemoryRoute
  '/orbita': typeof OrbitaRoute
  '/tower': typeof TowerRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/desktop': typeof DesktopRoute
  '/memory': typeof MemoryRoute
  '/orbita': typeof OrbitaRoute
  '/tower': typeof TowerRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/desktop': typeof DesktopRoute
  '/memory': typeof MemoryRoute
  '/orbita': typeof OrbitaRoute
  '/tower': typeof TowerRoute
  '/traces': typeof TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/desktop'
    | '/memory'
    | '/orbita'
    | '/tower'
    | '/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/desktop'
    | '/memory'
    | '/orbita'
    | '/tower'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/desktop'
    | '/memory'
    | '/orbita'
    | '/tower'
    | '/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DesktopRoute: typeof DesktopRoute
  MemoryRoute: typeof MemoryRoute
  OrbitaRoute: typeof OrbitaRoute
  TowerRoute: typeof TowerRoute
  TracesRoute: typeof TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbita': {
      id: '/orbita'
      path: '/orbita'
      fullPath: '/orbita'
      preLoaderRoute: typeof OrbitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tower': {
      id: '/tower'
      path: '/tower'
      fullPath: '/tower'
      preLoaderRoute: typeof TowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DesktopRoute: DesktopRoute,
  MemoryRoute: MemoryRoute,
  OrbitaRoute: OrbitaRoute,
  TowerRoute: TowerRoute,
  TracesRoute: TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
